# Generated by Django 5.0.4 on 2026-05-13 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barbershop_whatsapp_access_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='whatsapp_access_token',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='whatsapp_flow_id',
        ),
        migrations.CreateModel(
            name='WhatsAppFlow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo, ej: 'Reserva Principal'", max_length=100)),
                ('flow_id', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False, help_text='Marcar como el flujo principal para agendar')),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='core.barbershop')),
            ],
        ),
    ]
