# Generated by Django 5.0.4 on 2026-05-13 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_barbershop_whatsapp_access_token_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappflow',
            options={'verbose_name': 'WhatsApp Flow', 'verbose_name_plural': 'WhatsApp Flows'},
        ),
        migrations.AlterField(
            model_name='whatsappflow',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappflow',
            name='name',
            field=models.CharField(help_text="Ej: 'Flujo de Reserva Premium'", max_length=100),
        ),
        migrations.CreateModel(
            name='WhatsAppTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre de la plantilla en Meta (ej: 'welcome_msg')", max_length=100)),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('language_code', models.CharField(default='es_MX', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.barbershop')),
            ],
            options={
                'verbose_name': 'WhatsApp Template',
                'verbose_name_plural': 'WhatsApp Templates',
            },
        ),
    ]
