# Generated by Django 5.0.4 on 2026-05-13 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_whatsappflow_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbershop',
            name='owner',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='billing_address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Fiscal'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Facturación'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='client_name',
            field=models.CharField(blank=True, help_text='Nombre del contacto/dueño', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='legal_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Razón Social'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='RFC / Tax ID'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='wants_invoice',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Factura?'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='wants_ticket',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Ticket?'),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='name',
            field=models.CharField(help_text='Nombre comercial de la barbería', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='name',
            field=models.CharField(help_text='Nombre de la plantilla en Meta', max_length=100),
        ),
    ]
