# Generated by Django 5.0.4 on 2026-05-13 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_barbershop_owner_barbershop_billing_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Configuración Principal Meta', max_length=100)),
                ('app_id', models.CharField(blank=True, max_length=50, null=True)),
                ('app_secret', models.CharField(blank=True, max_length=100, null=True)),
                ('access_token', models.TextField(help_text='System User Access Token (Token de acceso permanente)')),
                ('verify_token', models.CharField(default='flowcuts_secret_token_2026', help_text='Token para verificar el Webhook en Meta', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Meta App Config',
                'verbose_name_plural': 'Meta App Config',
            },
        ),
    ]
