# Generated by Django 5.0.4 on 2026-05-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_metaconfig'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='whatsappflow',
            options={'verbose_name': 'WhatsApp Flow (Biblioteca)', 'verbose_name_plural': 'WhatsApp Flows (Biblioteca)'},
        ),
        migrations.AlterModelOptions(
            name='whatsapptemplate',
            options={'verbose_name': 'WhatsApp Template (Biblioteca)', 'verbose_name_plural': 'WhatsApp Templates (Biblioteca)'},
        ),
        migrations.RemoveField(
            model_name='whatsappflow',
            name='is_default',
        ),
        migrations.RemoveField(
            model_name='whatsappflow',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='whatsapptemplate',
            name='shop',
        ),
        migrations.AddField(
            model_name='barbershop',
            name='available_flows',
            field=models.ManyToManyField(blank=True, related_name='assigned_shops', to='core.whatsappflow'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='available_templates',
            field=models.ManyToManyField(blank=True, related_name='assigned_shops', to='core.whatsapptemplate'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='default_flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_shops', to='core.whatsappflow'),
        ),
        migrations.AddField(
            model_name='whatsappflow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='billing_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='legal_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='wants_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='wants_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metaconfig',
            name='access_token',
            field=models.TextField(help_text='System User Access Token'),
        ),
        migrations.AlterField(
            model_name='metaconfig',
            name='verify_token',
            field=models.CharField(default='teleferico_seguro_123', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsappflow',
            name='flow_id',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='whatsappflow',
            name='name',
            field=models.CharField(help_text='Nombre descriptivo del flujo', max_length=100),
        ),
        migrations.AlterField(
            model_name='whatsapptemplate',
            name='name',
            field=models.CharField(help_text='Nombre de la plantilla en Meta', max_length=100, unique=True),
        ),
    ]
