# Generated by Django 5.0.4 on 2026-05-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_whatsappflow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaconfig',
            name='test_payload',
            field=models.TextField(blank=True, help_text='Pega aquí un JSON de Meta para simular un mensaje', null=True),
        ),
    ]
