# Generated by Django 5.0.4 on 2026-05-13 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_description_service_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaconfig',
            name='catalog_id',
            field=models.CharField(blank=True, help_text='ID del catálogo de Meta Commerce', max_length=50, null=True),
        ),
    ]
