# Generated by Django 5.0.4 on 2026-05-14 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_metaconfig_catalog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='metaconfig',
            name='flow_private_key',
            field=models.TextField(blank=True, help_text='Llave Privada RSA para WhatsApp Flows', null=True),
        ),
        migrations.AddField(
            model_name='metaconfig',
            name='flow_public_key',
            field=models.TextField(blank=True, help_text='Llave Pública RSA para WhatsApp Flows', null=True),
        ),
    ]
