# Generated by Django 5.0.4 on 2026-05-20 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_metaconfig_flow_private_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección completa física', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitud para el mapa', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitud para el mapa', max_digits=9, null=True),
        ),
    ]
