# Generated by Django 5.0.4 on 2026-05-20 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_barbershop_address_barbershop_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='business_hours',
            field=models.CharField(blank=True, default='Lunes a Sábado de 10:00 AM a 8:00 PM', help_text='Horario de atención comercial', max_length=255, null=True),
        ),
    ]
