# Generated by Django 5.0.4 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_barbershop_business_hours'),
        ('partners', '__first__'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RemoveField(
                    model_name='partner',
                    name='user',
                ),
                migrations.AlterField(
                    model_name='barbershop',
                    name='referred_by',
                    field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_shops', to='partners.partner'),
                ),
                migrations.RemoveField(
                    model_name='service',
                    name='shop',
                ),
                migrations.RemoveField(
                    model_name='staff',
                    name='shop',
                ),
                migrations.DeleteModel(
                    name='Appointment',
                ),
                migrations.DeleteModel(
                    name='Partner',
                ),
                migrations.DeleteModel(
                    name='Service',
                ),
                migrations.DeleteModel(
                    name='Staff',
                ),
            ]
        )
    ]
