# Generated by Django 5.0.4 on 2026-05-20 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Partner',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('referral_code', models.CharField(max_length=20, unique=True)),
                        ('commission_rate', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                        ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                        ('current_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                        ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
                    ],
                    options={
                        'db_table': 'core_partner',
                    },
                ),
            ]
        ),
        migrations.CreateModel(
            name='CommissionPayout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=150)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_earned', models.DecimalField(decimal_places=2, max_digits=10)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='partners.partner')),
            ],
        ),
        migrations.CreateModel(
            name='PayoutLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pendiente de Pago'), ('paid', 'Transferido/Completado'), ('failed', 'Rechazado')], default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='partners.partner')),
            ],
        ),
    ]
