name: flowcuts_app
description: FlowCuts — App de administración para barberías
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  intl: ^0.19.0
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  animate_do: ^3.3.4
  flutter_slidable: ^3.1.1
  table_calendar: ^3.1.2
  fl_chart: ^0.69.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
