# Generated by Django 5.0.4 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_remove_partner_user_alter_barbershop_referred_by_and_more'),
        ('notifications', '0001_initial'),
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='scheduler.appointment'),
        ),
        migrations.AddField(
            model_name='whatsapptemplateconfig',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='core.barbershop'),
        ),
    ]
