# Generated by Django 5.0.4 on 2026-05-20 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0014_remove_partner_user_alter_barbershop_referred_by_and_more'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name='Service',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('description', models.TextField(blank=True, null=True)),
                        ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                        ('duration_minutes', models.PositiveIntegerField(default=30)),
                        ('image_url', models.URLField(blank=True, null=True)),
                        ('is_active', models.BooleanField(default=True)),
                        ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='core.barbershop')),
                    ],
                    options={
                        'db_table': 'core_service',
                    },
                ),
                migrations.CreateModel(
                    name='Staff',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=100)),
                        ('is_active', models.BooleanField(default=True)),
                        ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.barbershop')),
                    ],
                    options={
                        'db_table': 'core_staff',
                    },
                ),
                migrations.CreateModel(
                    name='Appointment',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('client_name', models.CharField(max_length=100)),
                        ('client_phone', models.CharField(max_length=20)),
                        ('start_time', models.DateTimeField()),
                        ('end_time', models.DateTimeField(blank=True, null=True)),
                        ('status', models.CharField(default='scheduled', max_length=20)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.barbershop')),
                        ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.service')),
                        ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='scheduler.staff')),
                    ],
                    options={
                        'db_table': 'core_appointment',
                    },
                ),
            ]
        ),
        migrations.CreateModel(
            name='TimeBlocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('reason', models.CharField(blank=True, max_length=150, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockers', to='scheduler.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_working', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='scheduler.staff')),
            ],
            options={
                'unique_together': {('staff', 'day_of_week')},
            },
        ),
    ]
